name: Check for broken links

# Triggers changed to manual dispatch to avoid long-running link checks on every push.
# If you want to run the link checker for a specific commit or branch, use the
# "Run workflow" button in the Actions tab or trigger via the API.
on:
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    # only run on the main repo
    if: github.repository == 'alshedivat/al-folio'
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          fail: true
          # removed md files that include liquid tags
          args: --user-agent 'curl/7.54' --exclude-path README.md --exclude-path _pages/404.md --exclude-path _pages/blog.md --exclude-path _posts/2018-12-22-distill.md --exclude-path _posts/2023-04-24-videos.md --exclude-path _books/the_godfather.md --verbose --no-progress './**/*.md' './**/*.html'
